# Generated by Django 5.0.7 on 2024-07-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guideapplication',
            options={'verbose_name': 'Список заявок на роль Гида', 'verbose_name_plural': 'Список заявок на роль Гида'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
    ]
