# Generated by Django 5.0.7 on 2024-07-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_guideapplication_options_alter_tour_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
