# Generated by Django 5.0.7 on 2024-07-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.guideapplication')),
            ],
        ),
    ]
