# Generated by Django 5.0.7 on 2024-07-24 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceToLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=350)),
                ('images', models.FileField(upload_to='place_to_live_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TourDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.PositiveIntegerField()),
                ('activityLevel', models.CharField(max_length=20)),
                ('comfortLevel', models.CharField(max_length=20)),
                ('languages', models.CharField(choices=[('english', 'English'), ('russian', 'Russian')], max_length=20)),
                ('journey', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=350)),
                ('images', models.FileField(upload_to='itinerary_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TourLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to='LocationImages/')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_person', models.PositiveIntegerField()),
                ('days', models.PositiveIntegerField()),
                ('start_day', models.DateTimeField()),
                ('end_day', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('images', models.FileField(upload_to='tours_images/')),
                ('included', models.CharField(max_length=200)),
                ('not_included', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place_to_live', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.placetolive')),
                ('description', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tourdescription')),
                ('itinerary', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.touritinerary')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tourlocation')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
