# Generated by Django 5.0.7 on 2024-07-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourlocation',
            name='content',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourlocation',
            name='image',
            field=models.FileField(default=1, upload_to='LocationImages/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toursteps',
            name='image',
            field=models.FileField(upload_to='StepsImages/'),
        ),
    ]
