# Generated by Django 5.0.7 on 2024-08-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tourlocation_content_tourlocation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='included',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='not_included',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='place_to_live',
        ),
        migrations.DeleteModel(
            name='TourItinerary',
        ),
        migrations.DeleteModel(
            name='TourSteps',
        ),
    ]
