# Generated by Django 5.0.7 on 2024-07-23 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_about_options_alter_tourlocation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tourlocation'),
        ),
    ]
