# Generated by Django 5.0.7 on 2024-07-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='num_people',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_num',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
